### ISSUE TITLE
Investigate Alternative Approaches for Error Code Object Generation

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#12]
The current method added by 3b0fdaf0819242cb6866b93f5378fee099edcc96 fixes the issue of attempting to share the same error instance across multiple occurrences of the linting error, but it's extremely repetitive & and there must be a cleaner way to implement it while retaining the same functionality.

**Comment by MarkKoz** [comment]
Here's an idea:

```py
def define_error(name: str, description: str):
    def init(self, argname: str, lineno: int, col_offset: int):
        Error.__init__(self, name, description)
        self.argname = argname
        self.lineno = lineno
        self.col_offset = col_offset

    globals()[name] = type(name, (Error,), {'__init__': init})


define_error("TYP201", "Missing return type annotation for public function")
```

Updating the global namespace is optional and probably better to not do so that IDEs can see the definitions exist.

**Comment by sco1** [comment]
I don't think there's much of an impending need to action this issue so will close for now.
