### ISSUE TITLE
Add handling for @property decorator

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#20]
The `@property` decorator was overlooked when creating the initial parsing logic.

Support for this should be added:

- [x] `ClassDecoratorType` enum constant
  * For the purposes of this tool, property, getter, setter, and deleter can probably safely be combined into a single `PROPERTY` constant
- [x] Handling by AST parser
- [x] Add error codes
- [x] Add error classification

**Comment by sco1** [comment]
I'm waffling back and forth on whether it's really necessary to give properties explicit handling.

`@classmethod` and `@staticmethod` need to be flagged separately; `@classmethod` because the verbiage is different from a regular class method (e.g. class vs. self), and `@staticmethod` because it doesn't have self/class input but is flagged as a class method. I don't see a rationale for separating property methods from the rest of the rest of the class methods after the above two cases are extracted.

Thoughts?

**Comment by MarkKoz** [comment]
I don't see a point, but if you've already done the work for it then no harm in leaving it in. More customisation and all...

**Comment by sco1** [comment]
I'm leaning towards tossing this, I can't think of a scenario where the class method and property method ignore/don't ignore flags would ever not be in sync, nor one where the additional detail provides value to the programmer.

Shiny is nice, but why bother testing & maintaining it if it provides no value.

**Comment by lemonsaurus** [comment]
eh, I'd keep it. I don't foresee much of a workload in testing and maintaining this, and you've already written the code.

**Comment by sco1** [comment]
Per discussions in #22, this addition adds many scenarios that cannot be adequately addressed within our tool's current scope. Without a compelling argument in support of properly adding this feature, I'm going to close this for now.
