### ISSUE TITLE
Ability to ignore ANN001 errors for specific argument names

### ISSUE THREAD

**Issue by sumnerevans** [python-discord/flake8-annotations#68]
**Description**
Add a new option like `allowed-unannotated-argument-names` which is a comma separated list of argument names that are fine to not have annotated.

**Rationale/Use Case**
Examples: often I need to ingest variables in my functions that I never use (callbacks from another library for example). In these cases, I often will just use `_` as my variable.

Here is an example of a GTK callback:
```python
    def on_download_all_click(self, _: Any):
        CacheManager.batch_download_songs(
            self.get_artist_song_ids(),
            before_download=lambda: self.update_artist_view(
                self.artist_id,
                order_token=self.update_order_token,
            ),
            on_song_download_complete=lambda i: self.update_artist_view(
                self.artist_id,
                order_token=self.update_order_token,
            ),
        )
```
it would be nice if I could avoid having to have the `Any` annotation here.

**Comment by sco1** [comment]
While a generalized case is not something we’re interested in pursuing, as string parsing introduces its own set of complexity, there could be a case here for a special-case flag for suppressing colloquial “dummy” argument names.
