### ISSUE TITLE
Bump flake8 to 3.8.x

### ISSUE THREAD

**Issue by sco1** [python-discord/flake8-annotations#79]
The 3.8.0 release of flake8 is approaching, bringing support for the walrus operator along with a smörgåsbord of other enhancements. See: [alpha release notes](https://flake8.pycqa.org/en/latest/release-notes/3.8.0.html).

Running `flake8-3.8.0a2` doesn't seem to introduce any regressions with our current release, but we can keep an eye on the alphas & bump the dependency once there is a proper release.

**Comment by sumnerevans** [comment]
I'm currently using the alpha, but I'm not seeing any `flake8-annotations` errors. Is that due to the dependency mismatch?

**Comment by sco1** [comment]
flake8 3.8 is out, so this can be unstalled & added to the next release.
