### ISSUE TITLE
ANN101/2 don't make sense

### ISSUE THREAD

**Issue by Dreamsorcerer** [python-discord/flake8-annotations#80]
The ANN101 and ANN102 rules, have a footnote which says to see some other documentation about how to annotate self/cls. However, the very first sentence of the first link says:

> In most cases the first argument of class and instance methods does not need to be annotated, and it is assumed to have the type of the containing class for instance methods, and a type object type corresponding to the containing class object for class methods.

It then only shows an example of annotating self, where it is needed for the return type. While the second link has countless examples where self is not annotated.

Therefore, I can't see why these rules exist, or why they are enabled by default.

**Comment by sco1** [comment]
See: #75
