### ISSUE TITLE
Add Flag to Suppress Warnings for Dynamically Typed Functions

### ISSUE THREAD

**Issue by Dreamsorcerer** [python-discord/flake8-annotations#87]
For consistency with mypy, it would be nice to have an option/rule that behaved the same way as mypy regarding typing of `__init__()`.

Currently, flake8-annotations always raises a violation if there is no return type annotation.

Mypy, however, raises an error if there are no annotations at all (as this would indicate an untyped function).
i.e. If there are any annotations on parameters, then a return type is not needed. The return type is only needed when there are no parameters in order to mark the function as statically typed.
e.g. `def __init__(self, foo: str):` and `def __init__(self) -> None:` are both correctly typed.

**Comment by sco1** [comment]
Suppressing `ANN204` will ignore these warnings.

**Comment by Dreamsorcerer** [comment]
Yes, but it doesn't give any violation for `def __init__(self):`, which Mypy does. Allowing or suppressing will result in different behaviour to Mypy (more lenient or more relaxed respectively).

So, to be consistent with Mypy, I'm expecting violations for:
`def __init__(self):`
but, no violations for:
`def __init__(self, foo: str):`

**Comment by Dreamsorcerer** [comment]
i.e. Mypy assumes an implicit return type of None for `__init__()`. But, there has to atleast 1 annotation somewhere in order for the function to be marked as statically typed. No annotations indicates a dynamically typed function.
So, standard practice for `def __init__(self):` is to add a return type annotation to mark it as statically typed.

**Comment by sco1** [comment]
Ok, I'm following now, sorry.

Right now we don't have a mechanism for discriminating between statically and dynamically typed functions like Mypy does ([not just for `__init__`](https://mypy.readthedocs.io/en/stable/getting_started.html#function-signatures-and-dynamic-vs-static-typing)). Adding something like `--allow-untyped-defs` a la Mypy's [`--disallow-untyped-defs`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-untyped-defs) shouldn't be too complicated to add and would be worthwhile to provide as a flag.

In the interim you could probably fake it with the `--suppress-non-returning` flag, though it's not really semantically what you're looking for.

**Comment by Dreamsorcerer** [comment]
Indeed, I actually just disabled that flag, as Mypy will complain about no return types on regular functions. It's only `__init__()` that gets an implicit return type.

**Comment by Dreamsorcerer** [comment]
Unfortunately, that doesn't really resolve the problem, although still a nice addition to have.

For me, I want to:

- ensure all functions are statically typed.
- not add a return type to `__init__()`, _unless_ it is required to make it statically typed (i.e. there are no typed parameters).

**Comment by Dreamsorcerer** [comment]
Expected results:

`def __init__(self, foo: int):` pass
`def __init__(self) -> None:` pass
`def __init__(self, foo):` fail
`def __init__(self):` fail
`def __init__(self, foo: int) -> None:` Maybe fail (or just allow the redundant return type).

**Comment by sco1** [comment]
Ok. I guess we'll have to take another look at your specific use case.

**Comment by sco1** [comment]
Hopefully I got it right this time, would you be interested in checking out the `dev-next` branch (#91) to verify that we are able to provide a behavior that Mypy users would expect?

**Comment by Dreamsorcerer** [comment]
I cloned the branch, however I'm unsure how to make flake8 load it as a plugin..

**Comment by MarkKoz** [comment]
@Dreamsorcerer run `pip install -U /path/to/clone/directory`

**Comment by Dreamsorcerer** [comment]
Perfect, seems to be working correctly with the extra argument enabled.
