### ISSUE TITLE
Version constraint prevents installation via Poetry

### ISSUE THREAD

**Issue by wanderrful** [python-discord/flake8-annotations#89]
**Describe the bug**

Using Python `^3.7` or `^3.8` in your `pyproject.toml` file (i.e. the default values that Poetry generates) prevents adding this package via `poetry add`:

```
[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - flake8-annotations requires Python >=3.6.1,<3.9

Because no versions of flake8-annotations match >2.2.0,<3.0.0
 and flake8-annotations (2.2.0) requires Python >=3.6.1,<3.9, flake8-annotations is forbidden.
So, because tool-belt depends on flake8-annotations (^2.2.0), version solving failed.
```

**To Reproduce**
- `poetry init --no-interaction` to initialize a new Poetry project. 
- The python version in your `pyproject.toml` file will be `^3.8` or `^3.7` by default
- `poetry add flake8` (works fine)
- `poetry add flake8-annotations` (throws the error described above)

**Version Information**

```bash
$ flake8 --version
3.8.3 (black: 0.2.0, flake8-bandit: 2.1.2, flake8-bugbear: 20.1.4, import-
order: 0.18.1, mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython
3.8.2 on Darwin
```

```bash
$ python -V
Python 3.8.2
```

**Comment by sco1** [comment]
Thanks for the ping

Looks like this has also been asked upstream: https://github.com/python-poetry/poetry/issues/2646
And answered: https://github.com/python-poetry/poetry/issues/1930#issuecomment-653906544

The default caret requirement of, say `^3.8` tells Poetry that your project is compatible with `[3.8, 4.0)`, but we currently do not guarantee compatibility with `>=3.9` so this is technically an incompatibility. This can be solved with a tilde requirement, `~3.8`, which would describe compatibility with `[3.8, 3.9)`.

While our dependency pinning change (see: https://github.com/python-discord/flake8-annotations/commit/e2f94527b6ee9bf5187174eb9bca9b9b94e2b9d4) is technically correct, I'm not sure it's worthwhile to insist on this if it clashes with existing project specs; in principle it's worthwhile, but it's not a hill worth dying on.

I'll try and revert the change this afternoon.
